import { useEffect, useMemo, useState } from "react";
import { FiArrowRight, FiPackage, FiRefreshCw, FiSearch, FiTruck, FiUser } from "react-icons/fi";
import AuthFetch from "../../services/AuthFetch";
import "../../css/AdminOrders.css";

const pretty=s=>s?s.charAt(0).toUpperCase()+s.slice(1):"Unknown";
const paymentStatusFor=order=>order?.paymentMethod==="cod"&&order?.status==="delivered"&&order?.paymentStatus==="pending"?"paid":order?.paymentStatus;
export default function AdminOrders(){
 const [orders,setOrders]=useState([]);const [status,setStatus]=useState("");const [query,setQuery]=useState("");const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(null);const [modal,setModal]=useState(null);
 const load=async()=>{setLoading(true);try{const suffix=status?`?status=${encodeURIComponent(status)}`:"";const res=await AuthFetch(`/api/admin/orders${suffix}`,{method:"GET"});const data=await res.json().catch(()=>[]);if(!res.ok)throw new Error(data?.message||"Could not load orders");setOrders(Array.isArray(data)?data:[]);}catch(e){setModal({title:"Orders unavailable",msg:e.message});setOrders([]);}finally{setLoading(false);}};
 useEffect(()=>{load();},[status]);
 const filtered=useMemo(()=>{const q=query.toLowerCase().trim();return orders.filter(o=>!q||`${o._id} ${o.user?.name||""} ${o.user?.email||""}`.toLowerCase().includes(q));},[orders,query]);
 const next=s=>s==="pending"?"shipped":s==="shipped"?"delivered":null;
 const update=async o=>{const ns=next(o.status);if(!ns)return;setBusy(o._id);try{const res=await AuthFetch(`/api/admin/orders/${o._id}/status`,{method:"PATCH",body:JSON.stringify({nextStatus:ns})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data?.message||"Update failed");await load();}catch(e){setModal({title:"Status update failed",msg:e.message});}finally{setBusy(null);}};
 return <main className="page-shell admin-orders-page">
  {modal&&<div className="toast-overlay" onMouseDown={()=>setModal(null)}><div className="toast-card" onMouseDown={e=>e.stopPropagation()}><h3>{modal.title}</h3><p>{modal.msg}</p><div className="toast-actions">{modal.confirm&&<button className="btn-ui secondary" onClick={()=>setModal(null)}>Back</button>}<button className={`btn-ui ${modal.confirm?"accent":""}`} onClick={()=>{const action=modal.confirm;if(action){setModal(null);action();}else setModal(null);}}>{modal.confirm?"Confirm change":"Done"}</button></div></div></div>}
  <div className="admin-orders-heading"><div><p className="eyebrow">Admin · fulfillment</p><h1 className="page-title">Order operations</h1><p className="page-copy">Review customer orders and move eligible orders through fulfillment.</p></div><button className="btn-ui secondary" onClick={load} disabled={loading}><FiRefreshCw/> Refresh</button></div>
  <div className="order-admin-stats"><div><strong>{orders.length}</strong><span>Visible orders</span></div><div><strong>{orders.filter(o=>o.status==="pending").length}</strong><span>Pending</span></div><div><strong>{orders.filter(o=>o.status==="shipped").length}</strong><span>Shipped</span></div><div><strong>${orders.reduce((s,o)=>s+Number(o.total||0),0).toFixed(2)}</strong><span>Order value</span></div></div>
  <div className="admin-order-toolbar"><div className="search-box"><FiSearch/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search order, customer or email"/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="pending">Pending</option><option value="shipped">Shipped</option><option value="delivered">Delivered</option><option value="cancelled">Cancelled</option></select></div>
  {loading?<div className="order-skeleton"/>:<div className="admin-order-list">{filtered.map(o=>{const ns=next(o.status);return <article className="admin-order-card" key={o._id}><div className="admin-order-head"><div><span className="order-number">#{o._id.slice(-8).toUpperCase()}</span><small>{new Date(o.createdAt).toLocaleString()}</small></div><span className={`order-pill status-${o.status}`}>{pretty(o.status)}</span></div><div className="admin-order-body"><div className="customer-cell"><FiUser/><div><strong>{o.user?.name||"Unknown customer"}</strong><small>{o.user?.email||"No email"}</small>{o.shippingAddress?.city&&<small>{o.shippingAddress.city}{o.shippingAddress.country?`, ${o.shippingAddress.country}`:""}</small>}</div></div><div className="order-item-summary"><FiPackage/><span>{o.items?.length||0} line item{(o.items?.length||0)===1?"":"s"}</span></div><div className="payment-cell"><small>{o.paymentMethod==="cod"?"Cash on delivery":"Card"}</small><strong>${Number(o.total).toFixed(2)}</strong></div></div><div className="admin-order-items">{(o.items||[]).map((it,i)=><span key={i}>{it.nameSnapshot} <b>×{it.qty}</b></span>)}</div><div className="admin-order-foot"><span className={`order-pill pay-${paymentStatusFor(o)}`}>{pretty(paymentStatusFor(o))}</span>{ns?<button className="btn-ui accent" disabled={busy===o._id} onClick={()=>setModal({title:`Mark as ${ns}?`,msg:`This will move order #${o._id.slice(-8).toUpperCase()} from ${o.status} to ${ns}.`,confirm:()=>update(o)})}>{busy===o._id?"Updating…":<>{o.status==="pending"?<FiTruck/>:"✓"} Mark {ns} <FiArrowRight/></>}</button>:<span className="fulfillment-done">No further action</span>}</div></article>})}{!filtered.length&&<div className="empty-state"><FiPackage/><h3>No orders match</h3><p>Try another filter or search.</p></div>}</div>}
 </main>;
}
